BOARD_TAG    = nano328
PROJECT_DIR       = /home/vanell/Documents/Measure_Box/src
USER_LIB_PATH    :=  $(PROJECT_DIR)/libs
ARDUINO_LIBS = LiquidCrystal SoftwareSerial Bounce2 TinyGPS SD GPS pin 
include /usr/share/Arduino-Makefile/Arduino.mk
